### ISSUE TITLE
Stage: User is able to submit hearing date with incorrect field 

### ISSUE THREAD

**Issue by gopal2020** [NYCPlanning/labs-zap-search#1059] opened 2019-12-06 14:14 UTC
Actual Result:  User is able to submit hearing date with incorrect field 

Expected Result:  User should not able to submit hearing date with incorrect field 

![image](https://user-images.githubusercontent.com/57265341/70329196-cdd03200-1808-11ea-83b0-6a022eb87dc6.png)

![image](https://user-images.githubusercontent.com/57265341/70329168-bbee8f00-1808-11ea-92ed-c6035bed80f2.png)

**Comment by andycochran** [comment] 2019-12-06 14:49
What does "incorrect" mean? What's wring with the which field? 

Looking at the screenshot, it seems like the hearing location is blank. Is that what you mean by incorrect? 

The only was I'm able to reproduce that is by entering a space in the location field. Our validation is just making sure that _any_ text has been entered in the location field. Perhaps we should instead check for ≥ alphanumeric character. 

This is an enhancement not a bug, and should not block launch.

**Comment by andycochran** [comment] 2019-12-06 15:08
Hmm… I read the screenshot wrong; didn't notice the highlighted second location field. 

So the issue is that there is text in the location field, but the validation doesn't think the text is valid, and the confirmation screen shows that field as blank. It seems that validation is not working correctly on the second location field.

**Comment by allthesignals** [comment] 2019-12-06 17:08
Yeah, I think this is a UX issue.

We can tackle this problem if and only if we get time to refactor the code behind this.

**Comment by trbmcginnis** [comment] 2020-02-18 20:19
@gopal2020 Would you mind providing a step-by-step on how to recreate this bug? I've been trying to recreate it and have not been able to

**Comment by trbmcginnis** [comment] 2020-02-18 20:23
@gopal2020 @andycochran @allthesignals Has anyone else been able to recreate this bug, and if so, would they mind providing the steps? Haven't bee successful at recreating it

**Comment by trbmcginnis** [comment] 2020-02-20 16:07
Unable to reproduce this issue. Closing the issue, will reopen if we run into this bug again.

**Closed by trbmcginnis** 2020-02-20 16:07 UTC
Labels: Bug, DCP-QA, Easy Win
