### ISSUE TITLE
Applicant name showing as Unknown when there is data in ZAP

### ISSUE THREAD

**Issue by bean75** [NYCPlanning/labs-zap-search#237] opened 2018-07-06 15:09 UTC
A number of projects are showing a null applicant field (which displays as "Unknown Applicant," correct?). Many of these seem to have proper data (this is a required field so it is VERY unlikely that it would be blank, and in fact ZAP records missing this field will usually display as "Unknown" since the system filled in that field during the data migration). 

Attaching pic - note that 4 records have applicants but are showing as "Unknown Applicant" the 5th is displaying as "Unknown" and that correctly reflects the ZAP record (have since corrected that in ZAP, so now all should have applicants).
![capture](https://user-images.githubusercontent.com/40247515/42386244-787e7590-812e-11e8-9e66-2f3aa0be7c03.PNG)

**Comment by allthesignals** [comment] 2018-07-06 15:51
@chriswhong not sure how I feel about sending down a string 'Unknown Applicant'. I think it should be the front end's job to handle this. But I know that it's sometimes necessary to coalesce stuff when the query depends on a valid entry:
https://github.com/NYCPlanning/labs-zap-api/blob/73a33012d551e0f0f297916cba0b0972e4ccb7c7/queries/projects/normalized-projects.sql#L5

We also know from experience that you can't _filter_ on Postgres null values, which is why we coalesce them in `WHERE` clauses. 

Here's an example record which @bean75 is saying should have an applicant name:
https://zap.planning.nyc.gov/projects/P2015K0351

When we get a response on a project detail view, we get a different value (`null`):
<img width="566" alt="screen shot 2018-07-06 at 11 47 11 am" src="https://user-images.githubusercontent.com/5004319/42388089-5ec8b00a-8112-11e8-91d7-d141c92fe3d5.png">

Here's the line in the show view: 
https://github.com/NYCPlanning/labs-zap-api/blob/73a33012d551e0f0f297916cba0b0972e4ccb7c7/queries/projects/show.sql#L10

So, I think we `coalesce` in the index view so that it's possible to search/filter, but is that true? @chriswhong do you remember why we coalesce in the first place? I feel like a better alternative is to throw out anything that is null.

Now the main issue:
I'm seeing a _left join_ here: https://github.com/NYCPlanning/labs-zap-api/blob/73a33012d551e0f0f297916cba0b0972e4ccb7c7/queries/projects/show.sql#L121

This means anything that doesn't match isn't joined in.

**Comment by allthesignals** [comment] 2018-07-09 14:19
Dupe of #223 ?

**Comment by allthesignals** [comment] 2018-07-09 14:57
Cross-posting from #223: 

> We're not showing co-applicants. We should include:
> contact
> applicant
> applicant-team
> We'd want to pull both of those roles. Just include first and last names, even for "contacts" where we were concerned about PII.

**Comment by chriswhong** [comment] 2018-07-10 11:45
![Customer_entities__account__contact_.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/580f65f4e41c721300d753c7/125516c66e82c728ace21e0d46cb8189378d8eac9dd6ba4db054e49d2c55184c2807a024658bf7178041740f1b0e1de82e4a4356bcbbd671f3e57862804e0ebfd0385826c06f15aeb1d44ab701ba21d81e8db4ef8b44d2f42f67b6d5db1063474f4dcbed5727a19141c95df54ae34f56a41b3f66ef732431.png)

From dynamics docs ^^, maybe what we are looking for is also in `account` table

**Closed** 2018-07-11 23:22 UTC
Labels: bug, in progress
