### ISSUE TITLE
Bug with project filters not updated

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-zap-search#131] opened 2018-06-25 17:13 UTC
@chriswhong
> We are seeing an issue where when the user unchecks ALL project statuses, it never updates the query params (the last one that was checked remains)

**Comment by allthesignals** [comment] 2018-06-25 17:17
This query throws an error, API issue: 

https://zap-api.planninglabs.nyc/projects?dcp_ceqrtype%5B%5D=Type%20I&dcp_ceqrtype%5B%5D=Type%20II&dcp_ceqrtype%5B%5D=Unknown&dcp_ceqrtype%5B%5D=Unlisted&dcp_publicstatus%5B%5D=&dcp_ulurp_nonulurp%5B%5D=Non-ULURP&dcp_ulurp_nonulurp%5B%5D=ULURP&page=1

**Comment by allthesignals** [comment] 2018-06-25 17:19
dcp_publicstatus[]: sent up as blank

**Comment by chriswhong** [comment] 2018-06-25 17:19
We have a WIP to make the API return the default for the above call ^^

The issue is with the frontend, once the last status checkbox is unchecked, the query params in the app still show &dcp_projectstatus='{whateverthelastcheckedonewas}'

**Comment by allthesignals** [comment] 2018-06-25 17:20
That's not what I'm seeing. Can you tell me the exact steps to reproduce? @chriswhong

**Comment by chriswhong** [comment] 2018-06-25 17:22
Uncheck project status checkboxes until only one remains checked, 'Filed' for example. 
Query params in the app should read `dcp_projectstatus=Filed`.

Uncheck 'Filed', the query params should be `dcp_projectstatus=`, but they still show `dcp_projectstatus=Filed`.

**Comment by allthesignals** [comment] 2018-06-25 17:28
@chriswhong did you check the console log when you unchecked filed? The server throws an error and the app can't continue after that because it's an unhandled error.

**Comment by allthesignals** [comment] 2018-06-25 17:30
App throws this error at that step:

> Error while processing route: show-geography Ember Data Request GET https://zap-api.planninglabs.nyc/projects returned a 404

API error is this:
> {"error":"error: syntax error at or near \")\""}

So what I think is happening is that an empty dcp_projectstatus is not considered null and doesn't trigger the default values. We should probably just not pass the values in if it's empty.

**Comment by chriswhong** [comment] 2018-06-25 17:32
In a local branch we made changes to the API so it no longer errors on that query.  Ember parachute seems to not want to update the query params if `values` is an empty array.

**Comment by allthesignals** [comment] 2018-06-25 17:33
ALright, so I should test this against that branch......

**Comment by allthesignals** [comment] 2018-06-25 17:33
What is the name of the branch

**Comment by chriswhong** [comment] 2018-06-28 21:07
This is no longer an issue, closing

**Closed by chriswhong** 2018-06-28 21:07 UTC
Labels: in progress
