### ISSUE TITLE
Dynamically render participant type labels in templates based on `project.teammemberrole`

### ISSUE THREAD

**Issue by godfreyyeung** [NYCPlanning/labs-zap-search#739] opened 2019-10-03 14:20 UTC
Now that we have the `project.teammemberrole` field, we can use it to dynamically display participant type labels on project cards and in forms (Recommendation), etc.

**Comment by hannahkates** [comment] 2019-10-03 14:35
Dupe of #714

**Closed by hannahkates** 2019-10-03 14:35 UTC
Labels: LUPP
