### ISSUE TITLE
losing my place on the map

### ISSUE THREAD

**Issue by DCPJK** [NYCPlanning/labs-zap-search#390] opened 2018-08-08 14:06 UTC
It's super handy to look up an address to see what projects are/have been around it.  However, when I go 'back' from a search it pops out to the whole map again.
Example 1: I click on a project to see what its about, then I go back and I lose my place
Example 2: It zooms into the address, but then I click another button to filter differently at it flies back out again.
Can this be addressed?
Sincerely, Jon.

**Comment by chriswhong** [comment] 2018-08-24 16:33
Duplicate of #300

**Closed** 2018-08-24 16:34 UTC
