### ISSUE TITLE
Stage: LUP user does not have the ability to upload documents for a specific recommendation, when submitting multiple recommendations  

### ISSUE THREAD

**Issue by ksinghprod** [NYCPlanning/labs-zap-search#1055] opened 2019-12-05 17:19 UTC
Browser: Chrome
Project: 25-27 Mercer Street

Expected Result: LUP user should have the ability to upload documents for a specific recommendation, when submitting multiple recommendations 

Actual Result: LUP user does not have the ability to upload documents for a specific recommendation, when submitting multiple recommendations  

Right now when submitting multiple recommendations manually, the uploaded documents get submitted for all of the recommendations 

Here, I only uploaded documents to one of the recommendations but after I submitted, they are showing up for both of the recommendations on CRM

![image](https://user-images.githubusercontent.com/57362229/70257865-2942e700-1759-11ea-8f5c-5b4ca96c0dbd.png)

![image](https://user-images.githubusercontent.com/57362229/70257900-3bbd2080-1759-11ea-8efd-fcbacdea698f.png)

![image](https://user-images.githubusercontent.com/57362229/70257970-5d1e0c80-1759-11ea-9f2c-1762e6929ee3.png)

**Comment by allthesignals** [comment] 2019-12-05 17:22
> Right now when submitting multiple recommendations manually, the uploaded documents get submitted for all of the recommendations

Thanks, but this is intended behavior for now.

Let's consider this an enhancement and move for a later addition.

**Comment by gopal2020** [comment] 2019-12-05 19:42
Will come back to soon,

**Comment by hannahkates** [comment] 2020-03-03 16:59
Duplicate of #928, closing.

**Closed by hannahkates** 2020-03-03 16:59 UTC
