### ISSUE TITLE
Build out map for project view

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-zap-search#31] opened 2018-06-13 16:54 UTC

**Comment by chriswhong** [comment] 2018-06-13 16:56
- Add a fixed map to the project view (Map should fitbounds to the geojson)
- Add mock up dummy geojson to be returned in the mirage response

**Comment by andycochran** [comment] 2018-06-13 18:05
This is a duplicate of #29.

**Closed** 2018-06-13 19:27 UTC
Labels: in progress
