### ISSUE TITLE
Address search

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-zap-search#207] opened 2018-07-02 16:17 UTC
Two competing approaches:

I want to find nearby projects proximate to an address
 -or- 
I want to find related projects for a specific address

**Comment by andycochran** [comment] 2018-07-09 15:10
Per client: Add GeoSearch input to map which simply zooms the map to the selected location.

**Comment by andycochran** [comment] 2018-07-09 15:47
duplicate of #255

**Closed by andycochran** 2018-07-09 15:47 UTC
Labels: to do
